name: Update external file

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # каждый час

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest file
        run: |
          curl -L -o wlDPI_mobile.txt https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/WHITE-CIDR-RU-checked.txt

      - name: Check for changes
        id: diff
        run: |
          git add wlDPI_mobile.txt
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Auto-update wlDPI_mobile.txt"
          git push

      - name: Send Telegram notification
        if: steps.diff.outputs.changed == 'true'
        run: |
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD)"

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ wlDPI_mobile.txt обновлён

🔗 Коммит: $COMMIT_URL"
