name: Update external file

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # каждый час
    
permissions:
  contents: write
  
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # важно для diff

      - name: Download latest file
        run: |
          curl -L -o wlDPI_mobile.txt https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/WHITE-CIDR-RU-checked.txt

      - name: Check for changes
        id: diff
        run: |
          git add wlDPI_mobile.txt
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Auto-update wlDPI_mobile.txt"
          git push

      - name: Calculate diff stats
        if: steps.diff.outputs.changed == 'true'
        id: stats
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            STATS=$(git diff HEAD~1 HEAD --numstat | awk '{added+=$1; deleted+=$2} END {print "+"added" / -"deleted}')
          else
            STATS="+0 / -0"
          fi
          echo "stats=$STATS" >> $GITHUB_OUTPUT

      - name: Send Telegram (+/- stats)
        if: steps.diff.outputs.changed == 'true'
        run: |
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD)"

          MESSAGE=$(cat <<EOF
          ✅ wlDPI_mobile.txt обновлён

          📊 Изменения: ${{ steps.stats.outputs.stats }}

          🔗 $COMMIT_URL
          EOF
          )
          
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                --data-urlencode text="$MESSAGE"
